spring:
  datasource:
    url: ${DB_URL}
    username:  ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security: DEBUG  # Spring Security 디버그 로그 활성화

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
      static: ${S3_STATIC}

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB