spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SWE9DB
    username:  swe9
    password: 234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security: DEBUG  # Spring Security 디버그 로그 활성화

cloud:
  aws:
    s3:
      bucket: swe9-image
    credentials:
      access-key: AKIATQZCSXU2V6ZFYDDY
      secret-key: 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
      static: ap-northeast-2